package com.groupsix.attendify.ui;

import org.netbeans.lib.awtextra.AbsoluteConstraints;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;

public class AttendanceRecord extends javax.swing.JFrame {

    private JPanel sectionPanel;
    private JList<String> sectionList;
    private DefaultListModel<String> sectionListModel;
    private JTable attendanceTable;
    private DefaultTableModel attendanceTableModel;
    
    
    public AttendanceRecord() {
        initComponents();
        this.setResizable(false);
        createSectionPanel();
        createAttendanceTable();
        populateSectionList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(128, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("ATTENDIFY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(jLabel1)
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 130));

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 0, 0), 3, true), "Attendance Record", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(128, 0, 0))); // NOI18N
        jPanel4.setToolTipText("");
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1030, 510));

        jPanel5.setBackground(new java.awt.Color(128, 0, 0));

        jButton1.setBackground(new java.awt.Color(240, 224, 36));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(128, 0, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(469, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(458, 458, 458))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1030, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void createAttendanceTable() {
        attendanceTableModel = new DefaultTableModel();
        attendanceTableModel.addColumn("Student ID");
        attendanceTableModel.addColumn("Last Name");
        attendanceTableModel.addColumn("First Name");
        attendanceTableModel.addColumn("Attendance Status");
        attendanceTableModel.addColumn("Image"); // Display column for image

        attendanceTable = new JTable(attendanceTableModel);
        JScrollPane tableScrollPane = new JScrollPane(attendanceTable);
        tableScrollPane.setPreferredSize(new Dimension(500, 450));
        attendanceTable.setRowHeight(100);
        // Register ImageRenderer for the "Image" column (adjust columnIndex accordingly)
        attendanceTable.getColumnModel().getColumn(4).setCellRenderer(new ImageRenderer());

        jPanel4.add(tableScrollPane, new AbsoluteConstraints(260, 30, 750, 450));
    }

    private void updateAttendanceTable(String selectedSection) {
        attendanceTableModel.setRowCount(0);

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/attendify", "safdar", "123456");

            String query = "SELECT DISTINCT s.studentNumber, s.lastName, s.firstName, s.attendanceStatus, s.imagePath " +
                           "FROM students s " +
                           "JOIN classes c ON s.section = c.section " +
                           "WHERE s.section=?";
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setString(1, selectedSection);

            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                String studentId = rs.getString("studentNumber");
                String lastName = rs.getString("lastName");
                String firstName = rs.getString("firstName");
                String attendanceStatus = rs.getString("attendanceStatus");
                String imagePath = rs.getString("imagePath");

                // Add data to the table model, including the image path
                attendanceTableModel.addRow(new Object[]{studentId, lastName, firstName, attendanceStatus, imagePath});
            }

            rs.close();
            pstmt.close();
            conn.close();

        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error fetching attendance records: " + e.getMessage());
        }
    }






    private void createSectionPanel() {
    sectionPanel = new JPanel();
    sectionPanel.setPreferredSize(new Dimension(300, 510)); // Adjust size as needed
    sectionPanel.setBackground(new java.awt.Color(255, 255, 102));
    sectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(128,0,0), 3, true), "Classes and Sections", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell Condensed", 1, 18), new java.awt.Color(128,0,0)));

    sectionListModel = new DefaultListModel<>();
    sectionList = new JList<>(sectionListModel);
    sectionList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    sectionList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            sectionListValueChanged(evt); // Added to handle selection events
        }
        
    });

    JScrollPane scrollPane = new JScrollPane(sectionList);
    scrollPane.setPreferredSize(new Dimension(240, 410)); // Adjust size as needed
    sectionPanel.add(scrollPane);

    // Add sectionPanel to jPanel4 with AbsoluteConstraints for left-side positioning
    jPanel4.add(sectionPanel, new AbsoluteConstraints(0, 20, 260, 450)); // Adjust coordinates and size as needed
}


private void populateSectionList() {
    try {
        // Load the MySQL JDBC driver
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Create a connection to the database
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/attendify", "safdar", "123456");

        // Query to fetch distinct class names, sections, and date inserted from classes table
        String query = "SELECT DISTINCT className, section, dateOfSessions FROM classes";
        PreparedStatement pstmt = conn.prepareStatement(query);

        // Execute the query
        ResultSet rs = pstmt.executeQuery();

        // Clear previous list
        sectionListModel.clear();

        // Iterate through result set and add class names with sections and date inserted to list
        while (rs.next()) {
            String className = rs.getString("className");
            String section = rs.getString("section");
            String dateInserted = rs.getString("dateOfSessions");
            sectionListModel.addElement(className + " - " + section + " - " + dateInserted);
        }

        // Close connection and statement
        rs.close();
        pstmt.close();
        conn.close();

    } catch (ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(this, "Error fetching class names, sections, and date inserted: " + e.getMessage());
    }
}




 private void sectionListValueChanged(javax.swing.event.ListSelectionEvent evt) {
    if (!evt.getValueIsAdjusting()) {
        String selectedValue = sectionList.getSelectedValue();
        if (selectedValue != null) {
            // Extract section from selectedValue
            String section = selectedValue.split(" - ")[1]; // Assumes the format "className - section - dateInserted"
            updateAttendanceTable(section);
        }
    }
}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Dashboard db = new Dashboard();
        db.setVisible(true);
        db.pack();
        db.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
